#!/bin/sh
#
# A hook script for checking the commit-msg and ensuring a Jira project work 
# item is included somewhere in the first line of the commit message. 
COMMIT_MSG_FIRST_LINE=$(head -n1 $1)

# The restriction of the Jira project key pattern comes from here: https://confluence.atlassian.com/adminjiraserver/changing-the-project-key-format-938847081.html
JIRA_KEY_PATTERN="[A-Z][A-Z_0-9]+"
JIRA_ITEM_PATTERN="${JIRA_KEY_PATTERN}-[0-9]+"

# We also need to let merge commits through
MERGE_COMMIT_PATTERN="Merge branch "

if [[ ! ${COMMIT_MSG_FIRST_LINE} =~ ${JIRA_ITEM_PATTERN} ]] && [[ ! "${COMMIT_MSG_FIRST_LINE}" =~ ^"${MERGE_COMMIT_PATTERN}" ]]; then
	echo "Error: missing Jira work item number in the first line of your commit message"
	exit 1
fi